[tool.ruff]
fix = true
show-fixes = true
line-length = 100
target-version = "py311"

select = [
  "I",        # iSort
  "F",        # PyFlakes
  "E", "W",   # pycodestyle
  "N",        # pep8-naming
  "D",        # flake8-docstyle
  "UP",       # pyupgrade
  "PL",       # pylint
  "Q",        # flake8-quotes
  "SIM",      # flake8-simplify
  "TID",      # flake8-tidy-imports
  "ARG",      # flake8-unused-arguments
  "B",        # flake8-bugbear
#  "PTH",      # flake8-use-pathlib
  "TCH",      # flake8-type-checking
  "RET",      # flake8-return
#  "ANN",      # flake8-annotations
  "C4",       # flake8-comprehensions
]

ignore = [
  "D202", # No blank lines allowed after function docstring
  "PLR2004", # Magic value used in comparison
  "D203", # 1 blank line required before class docstring
  "D212", # Multi-line docstring summary should start at the first line

  # Temporarily suppress
  "ARG002", # Unused method argument in class
  "RET505", # Missing return statement
  "PLW2901", # loop variable overwritten by assignment target
  "SIM105", # Use contextlib.suppress
  "ARG001", # Useless function argument
  "PLC1901",
  "PLR5501",
  "RET508",
  "E501", # line too long
]

[tool.ruff.pylint]

max-branches=25
max-returns=15
max-args=10
max-statements=50
