FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

## Install requirements
RUN apt update \
    && apt install --no-install-recommends -y \
    curl \
    tzdata \
    ca-certificates \
    openssl \
    sudo \
    git
