version: '3'

services:
  emulated_hue:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    restart: "no"
    volumes:
      - ..:/workspace/hass-emulated-hue
    #    network_mode: "host"
    ports:
      - '80:80'
      - '443:443'
      - '2100:2100/udp'
    command: /bin/sh -c "while sleep 1000; do :; done"

# Host networking is required for discovery development
# If discovery is needed in development, use a Linux machine or venv
# Host networking for Docker does not work on Windows or MacOS
