# This workflow will dispatch a build event to the base-image repository if the requirements are changed

name: Trigger Base Image Build

on:
  push:
    branches: [master]
    paths:
      - 'requirements.txt'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          curl -XPOST \
            -u "${{ secrets.GCHR_USERNAME}}:${{secrets.GHCR_PAT}}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" https://api.github.com/repos/hass-emulated-hue/base-image/dispatches \
            --data '{"event_type": "build_image"}'
          echo "Dispatch Successful"
