DOMAIN_LIGHT = "light"
DOMAIN_HOMEASSISTANT = "homeassistant"
SERVICE_TURN_ON = "turn_on"
SERVICE_TURN_OFF = "turn_off"

DOMAIN_PERSISTENT_NOTIFICATION = "persistent_notification"
SERVICE_PERSISTENT_NOTIFICATION_CREATE = "create"
SERVICE_PERSISTENT_NOTIFICATION_DISMISS = "dismiss"

ATTR_ENTITY_ID = "entity_id"
