DOMAIN_LIGHT = "light"
DOMAIN_HOMEASSISTANT = "homeassistant"
SERVICE_TURN_ON = "turn_on"
SERVICE_TURN_OFF = "turn_off"

DOMAIN_PERSISTENT_NOTIFICATION = "persistent_notification"
SERVICE_PERSISTENT_NOTIFICATION_CREATE = "create"
SERVICE_PERSISTENT_NOTIFICATION_DISMISS = "dismiss"

ATTR_ENTITY_ID = "entity_id"

HASS_ATTR_BRIGHTNESS = "brightness"
HASS_ATTR_COLOR_TEMP = "color_temp"
HASS_ATTR_XY_COLOR = "xy_color"
HASS_ATTR_HS_COLOR = "hs_color"
HASS_ATTR_RGB_COLOR = "rgb_color"
HASS_ATTR_EFFECT = "effect"
HASS_ATTR_TRANSITION = "transition"
HASS_ATTR_FLASH = "flash"
